service: blog-zendesk-fetch-attachments
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, "ap-northeast-1"}
  memorySize: 256
  timeout: 30
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
            - 's3:PutObject'
          Resource:
            - '*'
  environment: ${self:custom.environment.${self:provider.stage}}
functions:
  fetch:
    handler: src/handlers/fetch.handler
plugins:
  - serverless-step-functions
  - serverless-python-requirements
  - serverless-prune-plugin
stepFunctions: ${file(includes/state-machines.yml)}
custom:
  pythonRequirements:
    usePipenv: true
  prune:
    automatic: true
    number: 3
  environment:
    dev:
      STAGE: ${self:provider.stage}
      SECRET: dev/blog-zendesk-fetch-attachments
package:
  patterns:
    - '!./**'
    - ./src/**/*.py
